import type { Metadata } from "next";
import { AuthProvider } from "../../Providers";
import SideNavbar from "@/app/components/Navbars/SideNavbar";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// const roboto_init = Roboto({
//   subsets: ["latin"],
//   weight: ['300', '400', '500'],
//   variable: '--font-roboto',
// })

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={inter.className}>

            <div className="flex border " >

               <SideNavbar />
               {/* <nav>
                  <ul>
                     <li><a href="/dashboard">Dashboard</a></li>
                     <li><a href="/exercise">Exercise</a></li>
                     <li><a href="/food">Food</a></li>
                     <li><a href="/explore">Explore</a></li>
                     <li><a href="/profile">Profile</a></li>
                  </ul>
               </nav> */}

               <div className="flex-grow border pl-32">
                  {children}
               </div>

            </div>

         </body>
      </html>
   );
}

